version: '3'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    networks:
      - micros-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - micros-net

  micro-seguridad:
    build:
      context: ./micro-seguridad
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    networks:
      - micros-net

  micro-naturales:
    build:
      context: ./micro-naturales
      dockerfile: Dockerfile
    ports:
      - "8086:5000"
    networks:
      - micros-net
  redis:
        image: "redis:alpine"

  micro-notificaciones:
    build:
      context: ./micro-notificaciones
      dockerfile: Dockerfile
    ports:
      - "8083:5000"
    networks:
      - micros-net

  micro-usuarios:
    build:
      context: ./micro-usuarios
      dockerfile: Dockerfile
    ports:
      - "8084:5000"
    networks:
      - micros-net

networks:
  micros-net:
    driver: bridge